removed JSON -> XML conversion
Issung/GChan pull request #29
Opened 2023-03-22 03:08 UTC by RoyalJackal

Tell me if anything's wrong

2023-03-23 23:15 UTC, Issung requested changes
Looks much nicer, just a few basic changes

2023-03-23 23:15 UTC, Issung commented on GChan/Trackers/Sites/Thread_8Kun.cs
> +                    }
Every single place we do this 
```c#
using (var web = new WebClient())
{
    string json = web.DownloadString(JSONUrl);
    byte[] bytes = Encoding.ASCII.GetBytes(json);

    using (var stream = new MemoryStream(bytes))
    {
        using (var streamReader = new StreamReader(stream))
        {
            var jsonReader = new JsonTextReader(streamReader);
            jObject = JObject.Load(jsonReader);
        }
    }
}
``` 
We can simplify it to
```c#
using (var web = new WebClient())
{
    string json = web.DownloadString(JSONUrl);
    jObject = JObject.Parse(json);
}
```
Can you please do that change everywhere it is needed?

2023-03-23 23:15 UTC, Issung commented on GChan/Trackers/Sites/Board_4Chan.cs
> +                    .ToList();
I didn't think using Linq would be possible, it actually looks super clean and readable, great work!

2023-03-23 23:15 UTC, Issung commented on GChan/Trackers/Sites/Board_4Chan.cs
> +                    .Select(x => "http://boards.4chan.org/" + Url.Split('/')[3] + "/thread/" + x["no"])
This line threw an OutOfBoundsException, due to the `Url.Split('/')[3]`. To make the code simpler and easier to read just the `BoardCode` property instead. Check if this issue is in the `Board_8Kun.cs` class too and do the same fix if so.

2023-03-23 23:15 UTC, Issung commented on GChan/Trackers/Sites/Thread_4Chan.cs
> +                var timPath = Url.Split('/')[3] == "f" ? "filename" : "tim";
Can use `BoardCode` here again instead of `Url.Split('/')[3]`

2023-03-23 23:15 UTC, Issung commented on GChan/Trackers/Sites/Thread_4Chan.cs
> +                        new ImageLink(baseURL + post["tim"] + post["ext"],
`baseURL + post["tim"] + post["ext"]`  was defined above in `old` so you can reuse it here.

2023-03-23 23:15 UTC, Issung commented on GChan/Trackers/Sites/Thread_4Chan.cs
> +                    string rep = post["tim"] + (string) post["ext"];
I wonder what `rep` stood for... If you can think of a better name go for it, also is the `(string)` cast here needed?

2023-03-28 19:01 UTC, RoyalJackal commented
I believe that's it if i haven't miss anything. About `(string)` cast, `JToken` doesn't cast itself automatically if it's not concatenated to a string, so i used a solution that Rider has suggested to me.

2023-04-01 03:51 UTC, Issung approved these changes
Looking great

2023-04-01 03:56 UTC, merged

2023-04-01 03:58 UTC, Issung commented
This has cleaned up the code greatly, and you did a better job than I would have too, thank you very much for your contribution! It is greatly appreciated