Save post number in ImageLink, for ease of use in GenerateNewFilename
Issung/GChan pull request #32
Opened 2023-04-26 21:12 UTC by RoyalJackal

For the 8kun currently post id is being saved into the Tim variable as the actual tim is a string of some sort. Maybe Tim variable should be made into string so both 8kun and 4chan tims would be stored as strings?

2023-04-30 05:00 UTC, Issung requested changes
1 small change try to get the value in the intended type from the JTokens to avoid unecessary string allocations and more descriptive error messages.
Few things to think about for this class, as its behaviour is a bit different for each website.. But this was intended to be a small issue/PR so let's keep it that way.

Also please add your name to `AboutBox.cs` in the list of contributors :)

2023-04-30 05:00 UTC, Issung commented on GChan/Trackers/Sites/Thread_4Chan.cs
> +                            long.Parse(x["no"].ToString())))
Try doing `x["no"].Value<long>()` here and in other locations, test and see if it works as expected.

2023-05-06 00:59 UTC, Issung approved these changes
Looking great :)

2023-05-06 00:59 UTC, Issung commented
Merge when you're ready :)

2023-06-14 11:06 UTC, Issung commented
Are you ready to merge this PR?

2023-06-18 09:16 UTC, RoyalJackal commented
Yeah, merge it whenever you like.

2023-08-13 02:08 UTC, Issung approved these changes

2023-08-13 02:09 UTC, merged